DROP DATABASE IF EXISTS MyDb;
CREATE DATABASE IF NOT EXISTS MyDb;
USE MyDb;

CREATE TABLE t_user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(32) UNIQUE NOT NULL ,
    sex VARCHAR(4) DEFAULT '男'
);